### ISSUE TITLE
Code pool local

### ISSUE THREAD

**Issue by SchumacherFM** [AOEpeople/Aoe_ClassPathCache#18]
Hi there,

any reason why the code pool is local? Are you interested in changing that?
Got a lot of conflicts with that :-( 

Cheers, Cyrill

**Comment by SchumacherFM** [comment]
Won't fix :-(

**Comment by LeeSaferite** [comment]
Sorry for the monumental delay.  I've issued a pull request with the change. Hopefully it'll be merged tomorrow.

**Comment by SchumacherFM** [comment]
:+1:

**Comment by LeeSaferite** [comment]
Done
